const letterMap = new Map()

letterMap.set("a", "9xnku,4")
letterMap.set("b", "9mf89,4")
letterMap.set("c", "589v,3")
letterMap.set("d", "9xmla,4")
letterMap.set("e", "58df,3")
letterMap.set("f", "58dg,3")
letterMap.set("g", "9npuf,4")
letterMap.set("h", "9qmxl,4")
letterMap.set("i", "1j,1")
letterMap.set("j", "50mj,3")
letterMap.set("k", "9qpih,4")
letterMap.set("l", "5bfn,3")
letterMap.set("m", "higbw1,5")
letterMap.set("n", "9wl2z,4")
letterMap.set("o", "9me1i,4")
letterMap.set("p", "9xnk8,4")
letterMap.set("q", "9me2f,4")
letterMap.set("r", "5ib9,3")
letterMap.set("s", "58em,3")
letterMap.set("t", "5k0i,3")
letterMap.set("u", "5f1r,3")
letterMap.set("v", "hi926c,5")
letterMap.set("w", "vc1ci36,6")
letterMap.set("x", "5ewd,3")
letterMap.set("y", "5f0y,3")
letterMap.set("z", "9yafj,4")

export const letters = letterMap